### PR TITLE
Ukrainian translation

### PR DESCRIPTION
**Pull request by n0execution**

### CODE REVIEW

**Comment by 73VW** [comment]
Ouch it seems you haven't updated your branch before adding your ukrainian translation.

What I suggest you do: go back to the commit where your added ukrainian translation. (The Merge is shitty)
How: `git log` and find your commit id (the long hash)
Then: `git reset --hard <commit id>`
If my remote isn't in yours:
Run the following if you use ssh to push `git remote add source git@github.com:73VW/Publishing-to-PyPI-with-pbr-and-Travis.git`
or this if you use https: `git remote add source https://github.com/73VW/Publishing-to-PyPI-with-pbr-and-Travis.git`
Then: `git checkout -b Ukrainian_Translation`
Then: `git fetch source`
Then: `git reset --hard source/master`
Then: `git cherry-pick <commit id>`
Then: `git push --set-upstream origin Ukrainian_Translation`.
You now have a clean branch. Open a PR from the new branch.
Or in order to clean your master:
`git checkout master`
`git reset --hard source/master`
`git rebase Ukrainian_Translation`
`git push -f`
This should work.

**Comment by n0execution** [comment]
OMG. I'm a beginner in os contribution. Thanks!

**Comment by 73VW** [comment]
No problem 😉 
I am here to help anyway 😉

**Comment by 73VW** [comment]
No problem 😉 
I am here to help anyway 😉

**Pull request closed without merging**
